services:
  mysql:
    image: mysql:8.4
    container_name: learn-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: learn_auth
      MYSQL_USER: learn_auth
      MYSQL_PASSWORD: learn_auth_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_84_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7.2
    container_name: learn-auth-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_84_data:
